trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: $(githubHostEntry)
    sshKeySecureFile: $(githubDeployKey)
    sshPublicKey: $(githubPublicKey)
  displayName: 'Setup Github Environment'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    git config --global user.email "kamesh.sampath@hotmail.com"
    git config --global user.name "Red Hat Devx"
    npm install -g @antora/cli@2.0 -g @antora/site-generator-default@2.0 gh-pages@2.0.1   
  displayName: 'Install Tools and Packages'

- script: |
    antora --pull --stacktrace site.yml
  displayName: 'Generate Site'

- script: |
    touch gh-pages/.nojekyll
    gh-pages --dotfiles --message "Publishing new documentation **NO_CI**" --dist gh-pages
  displayName: 'Deploy Site'
