trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: "true"

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: $(githubHostEntry)
    sshKeySecureFile: $(githubDeployKey)
    sshPublicKey: $(githubPublicKey)
  displayName: 'Setup Github Environment'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @antora/cli@2.0 -g @antora/site-generator-default@2.0
  displayName: 'Install Tools and Packages'

- script: |
    git config --local user.email "kamesh.sampath@hotmail.com"
    git config --local user.name "Kamesh Sampath"
    git worktree add gh-pages gh-pages 
    antora --pull --stacktrace site.yml
  displayName: 'Generate Site'

- script: |
    cd gh-pages
    touch .nojekyll
    git add --all
    git commit --message "Publishing new documentation **NO_CI**"
    git push origin gh-pages
  displayName: 'Deploy Site'
