apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: tutorial-tools
      labels:
        app: tutorial-tools
    spec:
      containers:
        - name: tutorial-tools
          image: quay.io/rhdevelopers/tutorial-tools:0.0.4
          imagePullPolicy: IfNotPresent
          env:
            - name: MAVEN_MIRROR_URL
              value: "http://nexus.rhd-workshop-infra:8081/nexus/content/groups/public"
          workingDir: /projects
          resources:
            limits:
              cpu: 4
              memory: 4Gi
  - apiVersion: v1
    kind: Pod
    metadata:
      name: database
      labels:
        app: database
    spec:
      containers:
        - name: database
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - "--live"
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: POSTGRESQL_USER
              value: demo
            - name: POSTGRESQL_PASSWORD
              value: password
            - name: POSTGRESQL_DATABASE
              value: demodb
          ports:
            - containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
          image: >-
            image-registry.openshift-image-registry.svc:5000/openshift/postgresql
