runtime:
  cache_dir: ./.cache/antora

site:
  title: Quarkus Tutorial
  url: https://redhat-developer-demos.github.io/quarkus-tutorial
  start_page: quarkus-tutorial::index.adoc

content:
  sources:
    - url: git@github.com:redhat-developer-demos/quarkus-tutorial.git
      tags: []
      branches: release/*
      start_path: documentation
asciidoc:
  attributes:
    tutorial-namespace: tutorial
  extensions:
    - ./lib/copy-to-clipboard.js
    - ./lib/tab-block.js
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./gh-pages
