version: 2
jobs:
  antora:
    docker:
      - image: node:lts-jessie
    steps:
      - checkout
      - run:
          name: Install Antora and its dependencies
          command: |
            yarn global add @antora/cli@2.0
            yarn global add @antora/site-generator-default@2.0
      - run:
          name: Build docs
          command: antora --pull --stacktrace site.yml
      - persist_to_workspace:
          root: gh-pages
          paths:
            - "*"
  site-deploy:
    docker:
      - image: node:lts-jessie
    steps:
      - checkout
      - attach_workspace:
          at: gh-pages
      - run:
          name: Disable jekyll builds
          command: touch gh-pages/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            yarn  global add gh-pages@2.0.1
            git config user.email "kamesh.sampath@hotmail.com"
            git config user.name "Kamesh Sampath"
      - add_ssh_keys:
          fingerprints:
            - "d5:6a:de:6c:f9:08:e7:a9:ed:fb:4d:48:8c:5a:68:84"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Publishing new documentation" --dist gh-pages
workflows:
  version: 2
  build:
    jobs:
      - antora
      - site-deploy:
          requires:
            - antora
          filters:
            branches:
              only: master
