version: 2
jobs:
  antora:
    docker:
      - image: node:lts-jessie
    steps:
      - checkout
      - run:
          name: Install Antora and its dependencies
          command: |
            yarn global add @antora/cli@2.0
            yarn global add @antora/site-generator-default@2.0
      - run:
          name: Build docs
          command: antora --pull --stacktrace site.yml
      - persist_to_workspace:
          root: gh-pages
          paths:
            - "*"
  site-deploy:
    docker:
      - image: node:lts-jessie
    steps:
      - checkout
      - attach_workspace:
          at: gh-pages
      - run:
          name: Disable jekyll builds
          command: touch gh-pages/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            yarn  global add gh-pages@2.0.1
            git config user.email "kamesh.sampath@hotmail.com"
            git config user.name "Kamesh Sampath"
      - add_ssh_keys:
          fingerprints:
            - "c4:6e:01:ce:c9:32:73:e6:9f:ab:47:dc:21:08:98:d9"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Publishing new documentation" --dist gh-pages
workflows:
  version: 2
  build:
    jobs:
      - antora
      - site-deploy:
          requires:
            - antora
          filters:
            branches:
              only: /^release\/.*/
