kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: m2-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
spec:
  selector:
    app: $APP_NAME
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
        - name: quarkus
          image: docker.io/$REGISTRY_USER_NAME/$APP_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-web
              containerPort: 8080
          volumeMounts:
            - mountPath: /root/.m2
              name: m2-cache
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: m2-cache
          persistentVolumeClaim:
            claimName: m2-cache